### ISSUE TITLE
Conflict with spec build process?

### ISSUE THREAD

**Issue by silasjmatson** [farcaller/motion-redgreen#8]
Running `rake spec files=nonexistent_spec_name` somehow gets around the check that RubyMotion runs to ensure that the specified file exists, resulting in an error.

I have a barebones test app that reproduces the issue here: https://github.com/silasjmatson/testspecerror

**Comment by silasjmatson** [comment]
I'd guess the issue is here somewhere: https://github.com/farcaller/motion-redgreen/blob/master/lib/motion-redgreen/config.rb#L4-L16

**Comment by farcaller** [comment]
Unfortunately I haven't done any rubymotion development in nearly two years, so I have no idea how the compiler toolchain changed. I'll accept a PR if someone will figure out what's the problem though.

**Comment by mixflame** [comment]
I am doing rubymotion and If I end up using this gem I will patch the remaining tickets if I have time and it makes sense. Thanks
